### ISSUE TITLE
Error when activating ALRunner: The resource cannot be found. 

### ISSUE THREAD

**Issue by lvanvugt** [tfenster/ALRunner#1]
OK, started using your ALRunner, Tobi, and probably I am doing something wrong, but when applying the ALRunner I get the following error:
> Server Error in '/' Application.
> 
> The resource cannot be found. 
>   Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 
> 
>  Requested URL: /us/WebClient/default.aspx
> Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2103.2 

I am now on the August update of the New Dev Preview.

**Comment by tfenster** [comment]
You are probably doing a "Run" not a "Publish", right? Could you share your launch.json with me?

**Comment by lvanvugt** [comment]
I tried both.
See attachment.
[launch.zip](https://github.com/tfenster/ALRunner/files/1283630/launch.zip)

**Comment by tfenster** [comment]
Does F5 work?

**Comment by tfenster** [comment]
I just tried with the September Preview on a clean new system: it works there, so it probably isn't a local dependency. I remember having seen some issues about publishing and/or running with August update because of broken tenant settings. Could you maybe update to September and try there?

**Comment by lvanvugt** [comment]
F5 works fine. I will see on the September Preview. Is it already on Azure Gallery?

**Comment by tfenster** [comment]
Yes, it was released today (https://blogs.msdn.microsoft.com/nav/2017/09/07/nav-development-preview-september-update/) and available earlier through Docker

**Comment by tfenster** [comment]
Did you have a chance to check if it works in the meantime?

**Comment by lvanvugt** [comment]
Nope, unfortunately too busy with things like NAV TechDays. ;-)

Van: Tobias Fenster [mailto:notifications@github.com]
Verzonden: dinsdag 21 november 2017 09:49
Aan: tfenster/ALRunner <ALRunner@noreply.github.com>
CC: Luc van Vugt <lvanvugt@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [tfenster/ALRunner] Error when activating ALRunner: The resource cannot be found. (#1)


Did you have a chance to check if it works in the meantime?

**Comment by tfenster** [comment]
ok, I'll close it for now as it works for me and I know of a couple of colleagues also working with it. But if you get back to it and still have problems, please let me know
