### ISSUE TITLE
Command "ALRunner: Export diagnostics" has "|" char as field separator

### ISSUE THREAD

**Issue by XDNMarOli** [tfenster/ALRunner#11]
When exporting diagnostics with the command **"ALRunner: Export diagnostics"** the generated file use the **"|"** char as field separator when in a *.csv file the field separator must be **";"**

**Comment by tfenster** [comment]
@XDNMarOli thanks for the feedback but this is by design because ";" as separator too often clashes with coding error messages. Wherever you are using this, you can usually define the separator
