### ISSUE TITLE
Interested to demo your extension in a joined Areopa webinar?

### ISSUE THREAD

**Issue by lvanvugt** [tfenster/ALRunner#13]
Hey Tobi,

Are you interested in demoing your VSCode extension in a [Areopa](https://areopa.academy/) webinar?
The idea is to have AL VSCode extension domed to the community.

If you're interested please let me know. Mail to: webinars@areopa.academy.

b rg
Luc van Vugt

**Comment by tfenster** [comment]
@lvanvugt Thanks a lot for the offer but as my extension is so tiny and most of it is covered by other extensions by now, I don't think I can add meaningful content
