### ISSUE TITLE
Missing "error code" in .csv file when running ALRunner: Export diagnostics

### ISSUE THREAD

**Issue by HilmarVil** [tfenster/ALRunner#20]
The .csv file created by running ALRunner: Export diagnostics returns [object Object] where the error code is expected.  See sample below

file|error code|error message|start line|start char|end line|end char
Base\Codeunits\Activity Email Functions.codeunit.al|[object Object]|Codeunit 'SMTP Mail' is marked for removal. Reason: Replaced "Email Message" codeunit from "System Application".. Tag: 17.0.|205|23|205|34
Base\Codeunits\Activity Email Functions.codeunit.al|[object Object]|Codeunit 'SMTP Mail' is marked for removal. Reason: Replaced "Email Message" codeunit from "System Application".. Tag: 17.0.|483|51|483|62

This used to work fine.  Currently running this for an extension that has dependency on BC 19.1

**Comment by tfenster** [comment]
@HilmarVil thanks a lot for reporting this issue. I just now released a new version of the extension (3.3.2) which I hope fixes the problem. Could you please try that and let me know if it works for you as well?

**Comment by tfenster** [comment]
I had a typo in 3.3.2 and needed to release 3.3.3, which should now hopefully work

**Comment by HilmarVil** [comment]
@tfenster - I have tested the new version and this works like a charm now.  Thank you for the quick fix

**Comment by tfenster** [comment]
Thanks for the feedback
