### ISSUE TITLE
"ALRunner: Convert generated xlf to real one" does only create a <target> for first <source>

### ISSUE THREAD

**Issue by lvanvugt** [tfenster/ALRunner#5]
Hi Tobi,

Trying to use your new feature with the attached .xlf it only generates a <target> for the first <source>.
[SeminarRegistration.g.xlf.txt](https://github.com/tfenster/ALRunner/files/1878662/SeminarRegistration.g.xlf.txt)

**Comment by tfenster** [comment]
Just published 3.1.1 which should solve that problem. Could you please update and try again?

Thanks for bringing it up

**Comment by lvanvugt** [comment]
Tested and OK. Thanx for fixing it this fast.
