### ISSUE TITLE
ALRunner doesn't work on MacOs

### ISSUE THREAD

**Issue by dkatson** [tfenster/ALRunner#8]
Hi Tobias,
when i run 
![image](https://user-images.githubusercontent.com/29101017/46569765-61d30f00-c962-11e8-9191-f361cb97f5c0.png)
i get next error
command 'extension.generateObjectsFromURL' not found

I even don't get window to input next url
https://bridge.buddyweb.fr/api/icaoaircrafts/aircrafticaocodes

Unfortunately, no log is available (

**Comment by tfenster** [comment]
@dkatson Could you try to uninstall and re-install the "REST Client" extension (ALRunner relies on that extension)? If that works, could you test the following:

1. create a new file
1. set it's content to http (bottom right, there should be "plain text" and if you click on that you should get a dropdown of text files)
1. enter "GET http://example.com/api" in your new file and wait for a bit. "Send request" should appear above that line

In the end it should look like this:

![image](https://user-images.githubusercontent.com/15346084/46575689-4562c100-c9ba-11e8-83c6-4e5a867831da.png)

**Comment by tfenster** [comment]
@dkatson I have just pushed a new version of ALRunner with a couple of updated dependencies, maybe this also helps

**Comment by dkatson** [comment]
@tfenster works!
I've reinstalled ALRunner and REST extension.
Thank you!
 
![scr11](https://user-images.githubusercontent.com/29101017/46675404-f64da380-cbe6-11e8-8892-6bcfa4b72dad.gif)

**Comment by dkatson** [comment]
One thing. 
When I try to open Command pallet with base shortcut: Shift+Cmd+P, then i get error 
`Did not find a page or report object in the current line. Are you at the first line of a page or report?`
if i have .al file onpened.

Seems that you have reserved this shortcut for your extension, and it overwrites base shortcut

**Comment by tfenster** [comment]
@dkatson thanks for your feedback. I indeed have defined Shift+Cmd+P for "publish and run object". On Windows this is Shift+Alt+P, so it doesn't collide there. What would an appropriate combination on a Mac?

**Comment by dkatson** [comment]
What about Cmd+R ?

Dmitry

**Comment by tfenster** [comment]
@dkatson The current shortcuts are

Description | Windows | MacOS 
-- | -- | --
Run selection | Alt+R | Cmd+R
Run object on first line | Shift+Alt+R |  Cmd+Shift+R
Publish and run selection | Alt+P |  Cmd+P
Publish and run object on first line | Shift+Alt+P | Cmd+Shift+P

AFAIK all of that is fine, only Cmd+Shift+P on MacOS needs something else (and then it might make sense to also adjust Cmd+P
